# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lolsteak', '0002_auto_20160403_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='LolStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.IntegerField(choices=[(1, 'unranked'), (2, 'ranked')])),
                ('turrets_killed', models.IntegerField(default=0)),
                ('minions_killed', models.IntegerField(default=0)),
                ('neutral_minions_killed', models.IntegerField(default=0)),
                ('champions_killed', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Lol Stats',
            },
        ),
        migrations.AlterModelOptions(
            name='lolaccount',
            options={'verbose_name_plural': 'LOL Accounts'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='lolstat',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolsteak.LolAccount'),
        ),
    ]
